
--用户表
CREATE TABLE AN_USER (
  USER_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--日志表
CREATE TABLE AN_LOG (
  LOG_ID INT(11) NOT NULL AUTO_INCREMENT,
  LOG_OPERATOR INT(11) NOT NULL,
  LOG_DESC VARCHAR(255) NOT NULL,
  LOG_TIME DATETINE NOT NULL,
  PRIMARY KEY (LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
